package com.medibridge.core.db

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room DB Entity for storing Patient Summary and Side Effects.
 *
 * Implements Module C requirement for a dedicated table inside the existing AppDatabase.
 *
 * @property id Unique UUID for this summary record.
 * @property medicationId References [MedicationEntity.id].
 * @property patientSummary Plain-language patient friendly summary generated by Gemini.
 * @property sideEffects Structured JSON string or text with categorized side effects (common/serious).
 * @property generatedAt Unix epoch timestamp in milliseconds when generated.
 */
@Entity(
    tableName = "patient_summaries",
    indices = [Index(value = ["medicationId"], unique = true)]
)
data class PatientSummaryEntity(
    @PrimaryKey
    val id: String,

    val medicationId: String,

    val patientSummary: String,

    val sideEffects: String,

    val generatedAt: Long = System.currentTimeMillis()
)
