package com.medibridge.core.model

import com.medibridge.core.db.MedicationEntity
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

// ─────────────────────────────────────────────────────────────────────────────
// MedicationObject — THE SHARED CONTRACT for all 4 modules
//
// This is the ONLY authoritative representation of a medication in MediBridge.
// Modules A (Prescription), B (Safety), C (Schedule), and D (Shell/Chatbot)
// all read and write via this object.
//
// HOW TO EXTEND:
//   1. Add a field here with a sensible default (nullable or default val).
//   2. Add the same field (or a JSON-serialized form) to MedicationEntity.
//   3. Update toEntity() and fromEntity() extension functions below.
//   4. Bump the Room DB version in AppDatabase.kt and add a migration.
//
// DO NOT scatter medication fields across module-local data classes.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Represents a single dose conflict with another medication.
 * Populated by Module B (Safety Cross-Verification).
 */
data class MedicationConflict(
    /** ID of the conflicting medication (references another MedicationObject.id) */
    val withMedId: String,
    /** Type of conflict: e.g. "interaction", "duplicate", "contraindication" */
    val type: String,
    /** Human-readable detail for the patient/caregiver */
    val detail: String
)

/**
 * Represents a single scheduled dose slot.
 * Populated by Module C (Schedule Engine).
 */
data class ScheduleSlot(
    /** 24-hour time string e.g. "08:00" */
    val time: String,
    /** Named slot e.g. "Morning", "Afternoon", "Night" */
    val slot: String,
    /** Whether to take with food */
    val withFood: Boolean,
    /**
     * Start of the valid intake window (24-hour "HH:mm").
     * e.g. "06:00" for Morning. Null = use ±30min around [time].
     */
    val windowStart: String? = null,
    /**
     * End of the valid intake window (24-hour "HH:mm").
     * e.g. "09:00" for Morning. Null = use ±30min around [time].
     */
    val windowEnd: String? = null
)

/**
 * Tracks whether a specific day's dose was taken.
 * Written by Module D (Shell — user marks adherence) and Module C.
 */
data class AdherenceRecord(
    /** ISO date string e.g. "2024-11-01" */
    val date: String,
    /** "taken" | "missed" | "snoozed" */
    val status: String,
    /** Optional dose slot time e.g. "08:00" to uniquely distinguish multiple doses on the same day */
    val slotTime: String? = null
)

/**
 * Full, unpacked medication object — the single source of truth across all modules.
 *
 * All fields mirror [MedicationEntity] but JSON strings are unpacked into typed lists.
 * Use [toEntity] / [fromEntity] to persist and restore from Room DB.
 */
data class MedicationObject(

    // ── Identity ─────────────────────────────────────────────────────────────
    /** Unique ID (UUID string). Generated by Module A on first scan/entry. */
    val id: String,

    /** Medication name as extracted/entered. */
    val name: String,

    // ── Dosage Details ────────────────────────────────────────────────────────
    /** Strength e.g. "500mg", "10mg/5ml" */
    val strength: String,

    /** Dose unit/count e.g. "1 tablet", "5ml" */
    val dose: String,

    /** Human-readable frequency e.g. "Twice daily", "Every 8 hours" */
    val frequency: String,

    /** Timing relative to meals e.g. "After breakfast", "Before bed" */
    val timing: String,

    /** Duration of course e.g. "30 days", "5 days", "Ongoing" */
    val duration: String,

    // ── AI Confidence & Verification ─────────────────────────────────────────
    /**
     * Confidence score from Module A OCR/AI extraction (0.0 – 1.0).
     * Low confidence → needsVerification = true.
     */
    val confidence: Float,

    /** True if AI confidence < threshold or field is ambiguous. */
    val needsVerification: Boolean,

    /** True once the patient/caregiver has confirmed the details. */
    val verifiedByUser: Boolean,

    // ── Safety (Module B) ─────────────────────────────────────────────────────
    /**
     * True if Module B has run cross-verification against the full medication list.
     * False means safety check is pending.
     */
    val crossVerified: Boolean,

    /** List of detected conflicts with other medications. Empty if none. */
    val conflicts: List<MedicationConflict>,

    /** True if Module B recommends a doctor/pharmacist review. */
    val reviewRecommended: Boolean,

    // ── Schedule (Module C) ────────────────────────────────────────────────────
    /** Daily dose schedule generated by Module C. */
    val schedule: List<ScheduleSlot>,

    /** Adherence log — one entry per day the medication is active. */
    val adherence: List<AdherenceRecord>,

    // ── Patient-Facing Info ───────────────────────────────────────────────────
    /** Short plain-language summary shown on the home card. */
    val summary: String,

    /** List of common side effects as plain strings. */
    val sideEffects: List<String>,

    // ── Access Control (future multi-role feature) ────────────────────────────
    /**
     * Roles that can view this record e.g. ["patient", "caregiver", "doctor"].
     * Not enforced in hackathon shell; reserved for future auth layer.
     */
    val visibleTo: List<String>,

    // ── Media ─────────────────────────────────────────────────────────────────
    /** Optional URL/path for the prescription image (set by Module A). */
    val imageUrl: String? = null,

    // ── Extended Integration Fields (Modules A, C, D, E) ──────────────────────
    /** Tracks how this record entered system ("bill" or "voice"). */
    val sourceType: String = "bill",

    /** Voice-to-text transcribed summary from voice sessions (Module 1 / A). */
    val consultationNotes: String = "",

    /** Reference to mock bill image/data (Module A). */
    val billImageUrl: String? = null,

    /** Contact phone number for call reminders (Module E). */
    val caretakerPhone: String? = null,

    /** Call reminder status ("not_set", "pending_verification", "verified", "scheduled") (Module E). */
    val callReminderStatus: String = "not_set",

    /** Map keyed by role ("doctor", "caretaker", "pharmacy") holding role-specific summaries (Module D RBAC + Module C). */
    val privacySummary: Map<String, String> = emptyMap()
)

// ─────────────────────────────────────────────────────────────────────────────
// Extension functions — convert between domain object ↔ Room entity
// ─────────────────────────────────────────────────────────────────────────────

private val gson = Gson()

/** Converts a [MedicationObject] to a [MedicationEntity] for Room storage. */
fun MedicationObject.toEntity(): MedicationEntity = MedicationEntity(
    id = id,
    name = name,
    strength = strength,
    dose = dose,
    frequency = frequency,
    timing = timing,
    duration = duration,
    confidence = confidence,
    needsVerification = needsVerification,
    verifiedByUser = verifiedByUser,
    crossVerified = crossVerified,
    conflicts = gson.toJson(conflicts),
    reviewRecommended = reviewRecommended,
    schedule = gson.toJson(schedule),
    adherence = gson.toJson(adherence),
    summary = summary,
    sideEffects = gson.toJson(sideEffects),
    visibleTo = gson.toJson(visibleTo),
    imageUrl = imageUrl,
    sourceType = sourceType,
    consultationNotes = consultationNotes,
    billImageUrl = billImageUrl,
    caretakerPhone = caretakerPhone,
    callReminderStatus = callReminderStatus,
    privacySummary = gson.toJson(privacySummary)
)

/** Converts a [MedicationEntity] (Room row) back to a [MedicationObject]. */
fun MedicationEntity.fromEntity(): MedicationObject {
    val conflictType = object : TypeToken<List<MedicationConflict>>() {}.type
    val scheduleType = object : TypeToken<List<ScheduleSlot>>() {}.type
    val adherenceType = object : TypeToken<List<AdherenceRecord>>() {}.type
    val stringListType = object : TypeToken<List<String>>() {}.type
    val mapType = object : TypeToken<Map<String, String>>() {}.type

    return MedicationObject(
        id = id,
        name = name,
        strength = strength,
        dose = dose,
        frequency = frequency,
        timing = timing,
        duration = duration,
        confidence = confidence,
        needsVerification = needsVerification,
        verifiedByUser = verifiedByUser,
        crossVerified = crossVerified,
        conflicts = gson.fromJson(conflicts, conflictType) ?: emptyList(),
        reviewRecommended = reviewRecommended,
        schedule = gson.fromJson(schedule, scheduleType) ?: emptyList(),
        adherence = gson.fromJson(adherence, adherenceType) ?: emptyList(),
        summary = summary,
        sideEffects = gson.fromJson(sideEffects, stringListType) ?: emptyList(),
        visibleTo = gson.fromJson(visibleTo, stringListType) ?: emptyList(),
        imageUrl = imageUrl,
        sourceType = sourceType,
        consultationNotes = consultationNotes,
        billImageUrl = billImageUrl,
        caretakerPhone = caretakerPhone,
        callReminderStatus = callReminderStatus,
        privacySummary = gson.fromJson(privacySummary, mapType) ?: emptyMap()
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// Mock / Seed Data — used by HomeScreen while DB is empty (hackathon shell)
// Replace with real DB queries once Module A populates the database.
// ─────────────────────────────────────────────────────────────────────────────
val mockMedications: List<MedicationObject> = listOf(
    MedicationObject(
        id = "med-001",
        name = "Metformin",
        strength = "500mg",
        dose = "1 tablet",
        frequency = "Twice daily",
        timing = "After meals",
        duration = "90 days",
        confidence = 0.97f,
        needsVerification = false,
        verifiedByUser = true,
        crossVerified = true,
        conflicts = emptyList(),
        reviewRecommended = false,
        schedule = listOf(
            ScheduleSlot("08:00", "Morning", true),
            ScheduleSlot("20:00", "Night", true)
        ),
        adherence = emptyList(),
        summary = "Controls blood sugar. Take with food to reduce stomach upset.",
        sideEffects = listOf("Nausea", "Diarrhea", "Stomach pain"),
        visibleTo = listOf("patient", "doctor"),
        imageUrl = null,
        sourceType = "bill",
        consultationNotes = "Patient confirmed routine usage with meals.",
        billImageUrl = null,
        caretakerPhone = "+15550199",
        callReminderStatus = "verified",
        privacySummary = mapOf(
            "doctor" to "Doctor view: full medication history + conflicts",
            "caretaker" to "Caretaker view: schedule adherence & emergency info",
            "pharmacy" to "Pharmacy view: active prescriptions & refill status"
        )
    ),
    MedicationObject(
        id = "med-002",
        name = "Amlodipine",
        strength = "5mg",
        dose = "1 tablet",
        frequency = "Once daily",
        timing = "After breakfast",
        duration = "30 days",
        confidence = 0.91f,
        needsVerification = false,
        verifiedByUser = true,
        crossVerified = false,
        conflicts = listOf(
            MedicationConflict("med-003", "interaction", "May enhance hypotensive effect of Lisinopril")
        ),
        reviewRecommended = true,
        schedule = listOf(ScheduleSlot("09:00", "Morning", false)),
        adherence = emptyList(),
        summary = "Blood pressure medication. Avoid grapefruit juice.",
        sideEffects = listOf("Swelling of ankles", "Headache", "Flushing"),
        visibleTo = listOf("patient", "caregiver", "doctor"),
        imageUrl = null,
        sourceType = "voice",
        consultationNotes = "Doctor noted potential blood pressure drop with Lisinopril.",
        billImageUrl = null,
        caretakerPhone = null,
        callReminderStatus = "not_set",
        privacySummary = mapOf(
            "doctor" to "Doctor view: full medication history + conflicts",
            "caretaker" to "Caretaker view: schedule adherence & emergency info",
            "pharmacy" to "Pharmacy view: active prescriptions & refill status"
        )
    ),
    MedicationObject(
        id = "med-003",
        name = "Lisinopril",
        strength = "10mg",
        dose = "1 tablet",
        frequency = "Once daily",
        timing = "Before bed",
        duration = "60 days",
        confidence = 0.65f,
        needsVerification = true,
        verifiedByUser = false,
        crossVerified = false,
        conflicts = emptyList(),
        reviewRecommended = false,
        schedule = listOf(ScheduleSlot("22:00", "Night", false)),
        adherence = emptyList(),
        summary = "ACE inhibitor for heart & BP. Low AI confidence — please verify dose.",
        sideEffects = listOf("Dry cough", "Dizziness", "High potassium"),
        visibleTo = listOf("patient"),
        imageUrl = null,
        sourceType = "bill",
        consultationNotes = "",
        billImageUrl = null,
        caretakerPhone = null,
        callReminderStatus = "not_set",
        privacySummary = mapOf(
            "doctor" to "Doctor view: full medication history + conflicts",
            "caretaker" to "Caretaker view: schedule adherence & emergency info",
            "pharmacy" to "Pharmacy view: active prescriptions & refill status"
        )
    ),
    MedicationObject(
        id = "med-004",
        name = "Vitamin D3",
        strength = "1000 IU",
        dose = "1 softgel",
        frequency = "Once daily",
        timing = "After breakfast",
        duration = "Ongoing",
        confidence = 0.99f,
        needsVerification = false,
        verifiedByUser = true,
        crossVerified = true,
        conflicts = emptyList(),
        reviewRecommended = false,
        schedule = listOf(ScheduleSlot("09:00", "Morning", true)),
        adherence = emptyList(),
        summary = "Supplement for bone health and immunity.",
        sideEffects = listOf("Rare at normal doses"),
        visibleTo = listOf("patient"),
        imageUrl = null,
        sourceType = "voice",
        consultationNotes = "Daily supplement recommended by physician.",
        billImageUrl = null,
        caretakerPhone = null,
        callReminderStatus = "not_set",
        privacySummary = mapOf(
            "doctor" to "Doctor view: full medication history + conflicts",
            "caretaker" to "Caretaker view: schedule adherence & emergency info",
            "pharmacy" to "Pharmacy view: active prescriptions & refill status"
        )
    )
)
